// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrqharwfqittlynbjhrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhycWhhcndmcWl0dGx5bmJqaHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NzE4NjMsImV4cCI6MjA2ODU0Nzg2M30.9bswl1KNgw9bWrEKMIQ4pQ6_C7Mg_9yRYc0zDmfOMdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});